[package]
name = "bootloader"
version = "0.1.0"
authors = ["Ryland Morgan <ryland.hugo@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
shared = { path = "src/shared" }

[build-dependencies]
llvm-tools = "0.1"