[workspace]
members = [
  "bootsector",
  "stage_2"
]

[profile.release]
opt-level = "z"
panic = "abort"
lto = true

[profile.release.package.bootsector]
opt-level = "s"
codegen-units = 1

[profile.release.package.stage_2]
debug = true