[workspace]
members = [
  "bootsector",
  "stage_2"
]

[profile.release]
opt-level = "z"
panic = "abort"
lto = true

[profile.dev]
opt-level = "z"
panic = "abort"
lto = true
debug = true

[profile.release.package.bootsector]
opt-level = "s"
debug = false
codegen-units = 1